name: CI

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: yarn install, lint, build
        run: |
          yarn install
          yarn lint
          yarn build
